// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: hotstuff.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuorumCertPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blockid       []byte                 `protobuf:"bytes,1,opt,name=blockid,proto3" json:"blockid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumCertPayload) Reset() {
	*x = QuorumCertPayload{}
	mi := &file_hotstuff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumCertPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCertPayload) ProtoMessage() {}

func (x *QuorumCertPayload) ProtoReflect() protoreflect.Message {
	mi := &file_hotstuff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCertPayload.ProtoReflect.Descriptor instead.
func (*QuorumCertPayload) Descriptor() ([]byte, []int) {
	return file_hotstuff_proto_rawDescGZIP(), []int{0}
}

func (x *QuorumCertPayload) GetBlockid() []byte {
	if x != nil {
		return x.Blockid
	}
	return nil
}

type QuorumCertProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *QuorumCertPayload     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumCertProto) Reset() {
	*x = QuorumCertProto{}
	mi := &file_hotstuff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumCertProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCertProto) ProtoMessage() {}

func (x *QuorumCertProto) ProtoReflect() protoreflect.Message {
	mi := &file_hotstuff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCertProto.ProtoReflect.Descriptor instead.
func (*QuorumCertProto) Descriptor() ([]byte, []int) {
	return file_hotstuff_proto_rawDescGZIP(), []int{1}
}

func (x *QuorumCertProto) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *QuorumCertProto) GetPayload() *QuorumCertPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BlockPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        []byte                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Justify       *QuorumCertProto       `protobuf:"bytes,3,opt,name=justify,proto3" json:"justify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockPayload) Reset() {
	*x = BlockPayload{}
	mi := &file_hotstuff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPayload) ProtoMessage() {}

func (x *BlockPayload) ProtoReflect() protoreflect.Message {
	mi := &file_hotstuff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPayload.ProtoReflect.Descriptor instead.
func (*BlockPayload) Descriptor() ([]byte, []int) {
	return file_hotstuff_proto_rawDescGZIP(), []int{2}
}

func (x *BlockPayload) GetParent() []byte {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *BlockPayload) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *BlockPayload) GetJustify() *QuorumCertProto {
	if x != nil {
		return x.Justify
	}
	return nil
}

type BlockProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *BlockPayload          `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockProto) Reset() {
	*x = BlockProto{}
	mi := &file_hotstuff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockProto) ProtoMessage() {}

func (x *BlockProto) ProtoReflect() protoreflect.Message {
	mi := &file_hotstuff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockProto.ProtoReflect.Descriptor instead.
func (*BlockProto) Descriptor() ([]byte, []int) {
	return file_hotstuff_proto_rawDescGZIP(), []int{3}
}

func (x *BlockProto) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BlockProto) GetPayload() *BlockPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BlockProto) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_hotstuff_proto protoreflect.FileDescriptor

const file_hotstuff_proto_rawDesc = "" +
	"\n" +
	"\x0ehotstuff.proto\x12\bhotstuff\"-\n" +
	"\x11QuorumCertPayload\x12\x18\n" +
	"\ablockid\x18\x01 \x01(\fR\ablockid\"X\n" +
	"\x0fQuorumCertProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x125\n" +
	"\apayload\x18\x02 \x01(\v2\x1b.hotstuff.QuorumCertPayloadR\apayload\"o\n" +
	"\fBlockPayload\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\fR\x06parent\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x123\n" +
	"\ajustify\x18\x03 \x01(\v2\x19.hotstuff.QuorumCertProtoR\ajustify\"f\n" +
	"\n" +
	"BlockProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x120\n" +
	"\apayload\x18\x02 \x01(\v2\x16.hotstuff.BlockPayloadR\apayload\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06heightB\x04Z\x02./b\x06proto3"

var (
	file_hotstuff_proto_rawDescOnce sync.Once
	file_hotstuff_proto_rawDescData []byte
)

func file_hotstuff_proto_rawDescGZIP() []byte {
	file_hotstuff_proto_rawDescOnce.Do(func() {
		file_hotstuff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotstuff_proto_rawDesc), len(file_hotstuff_proto_rawDesc)))
	})
	return file_hotstuff_proto_rawDescData
}

var file_hotstuff_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hotstuff_proto_goTypes = []any{
	(*QuorumCertPayload)(nil), // 0: hotstuff.QuorumCertPayload
	(*QuorumCertProto)(nil),   // 1: hotstuff.QuorumCertProto
	(*BlockPayload)(nil),      // 2: hotstuff.BlockPayload
	(*BlockProto)(nil),        // 3: hotstuff.BlockProto
}
var file_hotstuff_proto_depIdxs = []int32{
	0, // 0: hotstuff.QuorumCertProto.payload:type_name -> hotstuff.QuorumCertPayload
	1, // 1: hotstuff.BlockPayload.justify:type_name -> hotstuff.QuorumCertProto
	2, // 2: hotstuff.BlockProto.payload:type_name -> hotstuff.BlockPayload
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hotstuff_proto_init() }
func file_hotstuff_proto_init() {
	if File_hotstuff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotstuff_proto_rawDesc), len(file_hotstuff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotstuff_proto_goTypes,
		DependencyIndexes: file_hotstuff_proto_depIdxs,
		MessageInfos:      file_hotstuff_proto_msgTypes,
	}.Build()
	File_hotstuff_proto = out.File
	file_hotstuff_proto_goTypes = nil
	file_hotstuff_proto_depIdxs = nil
}
